In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
!pip

Usage:
  pip3 <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --debug                     Let unhandled exceptions propagate outside the
                              main subroutine, instead of logging them to
                              stderr.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user configuration.
  --require-virtualenv        Allow pip to only run in a virtual environment;
                              exit with an error otherwise.
  --python <python>           Run pip with the specified Python interpreter.
  -v, --verbose               Give more output. Option is additive, and can be
                              used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be
                              used up to 3 times (corresponding to WARNING,
                              ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --keyring-provider <keyring_provider>
                              Enable the credential lookup via the keyring
                              library if user input is allowed. Specify which
                              mechanism to use [disabled, import, subprocess].
                              (default: disabled)
  --proxy <proxy>             Specify a proxy in the form
                              scheme://[user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should
                              attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists:
                              (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted,
                              even though it does not have valid or any HTTPS.
  --cert <path>               Path to PEM-encoded CA certificate bundle. If
                              provided, overrides the default. See 'SSL
                              Certificate Verification' in pip documentation
                              for more information.
  --client-cert <path>        Path to SSL client certificate, a single file
                              containing the private key and the certificate
                              in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output.
  --no-python-version-warning
                              Silence deprecation warnings for upcoming
                              unsupported Pythons.
  --use-feature <feature>     Enable new functionality, that may be backward
                              incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be
                              removed in the future.

In [3]:
!cat /proc/cpuinfo

processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi its
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 79
model name	: Intel(R) Xeon(R) CPU @ 2.20GHz
stepping	: 0
microcode	: 0xffffffff
cpu MHz		: 2199.998
cache size	: 56320 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 1
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch ssbd ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm rdseed adx smap xsaveopt arat md_clear arch_capabilities
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs taa mmio_stale_data retbleed bhi its
bogomips	: 4399.99
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:

In [4]:
#importing pandas
import pandas as pd
#loading data into dataframe
data_frame=pd.read_csv('/content/drive/MyDrive/Mall_Customers (1).csv')

In [6]:
#displaying first five rows
data_frame.head()

   CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male  19.0                15.0                     NaN
1           2    Male   NaN                15.0                    81.0
2           3  Female  20.0                16.0                     6.0
3           4  Female  23.0                 NaN                    77.0
4           5  Female   NaN                 NaN                    40.0

In [7]:
#If you want to get the first 10 rows, then you need to give the range in the parameters
data_frame.head(10)

   CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male  19.0                15.0                     NaN
1           2    Male   NaN                15.0                    81.0
2           3  Female  20.0                16.0                     6.0
3           4  Female  23.0                 NaN                    77.0
4           5  Female   NaN                 NaN                    40.0
5           6  Female  22.0                17.0                    76.0
6           7  Female   NaN                18.0                     6.0
7           8  Female  23.0                18.0                    94.0
8           9    Male  64.0                19.0                     3.0
9          10  Female  30.0                19.0                    72.0

In [8]:
data_frame.tail()

     CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female  35.0               120.0                    79.0
196         197  Female  45.0               126.0                    28.0
197         198    Male  32.0               126.0                    74.0
198         199    Male  32.0               137.0                    18.0
199         200    Male  30.0               137.0                    83.0

In [9]:
# Program to print all the column names of the data_frame
list(data_frame.columns)

['CustomerID', 'Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)']

In [10]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     197 non-null    float64
 3   Annual Income (k$)      198 non-null    float64
 4   Spending Score (1-100)  199 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 7.9+ KB

In [12]:
data_frame.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  197.000000          198.000000              199.000000
mean   100.500000   39.000000           61.005051               50.256281
std     57.879185   14.002915           26.017857               25.876350
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   29.000000           42.250000               34.500000
50%    100.500000   36.000000           62.000000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [13]:
data_frame.describe(include='object')

        Gender
count      200
unique       2
top     Female
freq       112

In [14]:
data_frame.shape

(200, 5)

In [15]:
data_frame.isnull().sum()

CustomerID                0
Gender                    0
Age                       3
Annual Income (k$)        2
Spending Score (1-100)    1
dtype: int64

In [16]:
data_frame.isna().sum()/len(data_frame)*100

CustomerID                0.0
Gender                    0.0
Age                       1.5
Annual Income (k$)        1.0
Spending Score (1-100)    0.5
dtype: float64

In [17]:
data_frame.head(15)

    CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0            1    Male  19.0                15.0                     NaN
1            2    Male   NaN                15.0                    81.0
2            3  Female  20.0                16.0                     6.0
3            4  Female  23.0                 NaN                    77.0
4            5  Female   NaN                 NaN                    40.0
5            6  Female  22.0                17.0                    76.0
6            7  Female   NaN                18.0                     6.0
7            8  Female  23.0                18.0                    94.0
8            9    Male  64.0                19.0                     3.0
9           10  Female  30.0                19.0                    72.0
10          11    Male  67.0                19.0                    14.0
11          12  Female  35.0                19.0                    99.0
12          13  Female  58.0                20.0                    15.0
13          14  Female  24.0                20.0                    77.0
14          15    Male  37.0                20.0                    13.0

In [18]:
data_frame.drop(4,inplace=True)
data_frame.head()

   CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male  19.0                15.0                     NaN
1           2    Male   NaN                15.0                    81.0
2           3  Female  20.0                16.0                     6.0
3           4  Female  23.0                 NaN                    77.0
5           6  Female  22.0                17.0                    76.0

In [19]:
data_frame.drop(data_frame.index[[1,3]],inplace=True)

In [20]:
data_frame.drop('CustomerID',axis=1,inplace=True)
data_frame.head()

   Gender   Age  Annual Income (k$)  Spending Score (1-100)
0    Male  19.0                15.0                     NaN
2  Female  20.0                16.0                     6.0
5  Female  22.0                17.0                    76.0
6  Female   NaN                18.0                     6.0
7  Female  23.0                18.0                    94.0

In [21]:
data_frame.drop(['Gender','Age'],axis=1,inplace=True)
data_frame.head()

   Annual Income (k$)  Spending Score (1-100)
0                15.0                     NaN
2                16.0                     6.0
5                17.0                    76.0
6                18.0                     6.0
7                18.0                    94.0

In [22]:
##import pandas
import pandas as pd

## load the datfram
data_frame = pd.read_csv('/content/drive/MyDrive/Mall_Customers (1).csv')
data_frame.rename({'CustomerID':"ID",'Gender':'Sex','Annual Income (k$)':'Salary'},axis=1,inplace=True)
data_frame.head()

   ID     Sex   Age  Salary  Spending Score (1-100)
0   1    Male  19.0    15.0                     NaN
1   2    Male   NaN    15.0                    81.0
2   3  Female  20.0    16.0                     6.0
3   4  Female  23.0     NaN                    77.0
4   5  Female   NaN     NaN                    40.0

In [23]:
data_frame['Sex'] = data_frame['Sex'].map({'Male':1,'Female':2})
data_frame.head()

   ID  Sex   Age  Salary  Spending Score (1-100)
0   1    1  19.0    15.0                     NaN
1   2    1   NaN    15.0                    81.0
2   3    2  20.0    16.0                     6.0
3   4    2  23.0     NaN                    77.0
4   5    2   NaN     NaN                    40.0

In [24]:
import pandas as pd
data_frame = pd.read_csv('/content/drive/MyDrive/Mall_Customers (1).csv')
data_frame.rename({'CustomerID':"ID", 'Gender':"Sex", 'Annual Income (k$)':"Salary"}, axis=1, inplace=True)
data_frame.head()

   ID     Sex   Age  Salary  Spending Score (1-100)
0   1    Male  19.0    15.0                     NaN
1   2    Male   NaN    15.0                    81.0
2   3  Female  20.0    16.0                     6.0
3   4  Female  23.0     NaN                    77.0
4   5  Female   NaN     NaN                    40.0

In [25]:
data_frame['Sex'].unique()

array(['Male', 'Female'], dtype=object)

In [26]:
!pip

Usage:
  pip3 <command> [options]

Commands:
  install                     Install packages.
  download                    Download packages.
  uninstall                   Uninstall packages.
  freeze                      Output installed packages in requirements format.
  inspect                     Inspect the python environment.
  list                        List installed packages.
  show                        Show information about installed packages.
  check                       Verify installed packages have compatible dependencies.
  config                      Manage local and global configuration.
  search                      Search PyPI for packages.
  cache                       Inspect and manage pip's wheel cache.
  index                       Inspect information available from package indexes.
  wheel                       Build wheels from your requirements.
  hash                        Compute hashes of package archives.
  completion                  A helper command used for command completion.
  debug                       Show information useful for debugging.
  help                        Show help for commands.

General Options:
  -h, --help                  Show help.
  --debug                     Let unhandled exceptions propagate outside the
                              main subroutine, instead of logging them to
                              stderr.
  --isolated                  Run pip in an isolated mode, ignoring
                              environment variables and user configuration.
  --require-virtualenv        Allow pip to only run in a virtual environment;
                              exit with an error otherwise.
  --python <python>           Run pip with the specified Python interpreter.
  -v, --verbose               Give more output. Option is additive, and can be
                              used up to 3 times.
  -V, --version               Show version and exit.
  -q, --quiet                 Give less output. Option is additive, and can be
                              used up to 3 times (corresponding to WARNING,
                              ERROR, and CRITICAL logging levels).
  --log <path>                Path to a verbose appending log.
  --no-input                  Disable prompting for input.
  --keyring-provider <keyring_provider>
                              Enable the credential lookup via the keyring
                              library if user input is allowed. Specify which
                              mechanism to use [disabled, import, subprocess].
                              (default: disabled)
  --proxy <proxy>             Specify a proxy in the form
                              scheme://[user:passwd@]proxy.server:port.
  --retries <retries>         Maximum number of retries each connection should
                              attempt (default 5 times).
  --timeout <sec>             Set the socket timeout (default 15 seconds).
  --exists-action <action>    Default action when a path already exists:
                              (s)witch, (i)gnore, (w)ipe, (b)ackup, (a)bort.
  --trusted-host <hostname>   Mark this host or host:port pair as trusted,
                              even though it does not have valid or any HTTPS.
  --cert <path>               Path to PEM-encoded CA certificate bundle. If
                              provided, overrides the default. See 'SSL
                              Certificate Verification' in pip documentation
                              for more information.
  --client-cert <path>        Path to SSL client certificate, a single file
                              containing the private key and the certificate
                              in PEM format.
  --cache-dir <dir>           Store the cache data in <dir>.
  --no-cache-dir              Disable the cache.
  --disable-pip-version-check
                              Don't periodically check PyPI to determine
                              whether a new version of pip is available for
                              download. Implied with --no-index.
  --no-color                  Suppress colored output.
  --no-python-version-warning
                              Silence deprecation warnings for upcoming
                              unsupported Pythons.
  --use-feature <feature>     Enable new functionality, that may be backward
                              incompatible.
  --use-deprecated <feature>  Enable deprecated functionality, that will be
                              removed in the future.

In [27]:
!apt

apt 2.4.14 (amd64)
Usage: apt [options] command

apt is a commandline package manager and provides commands for
searching and managing as well as querying information about packages.
It provides the same functionality as the specialized APT tools,
like apt-get and apt-cache, but enables options more suitable for
interactive use by default.

Most used commands:
  list - list packages based on package names
  search - search in package descriptions
  show - show package details
  install - install packages
  reinstall - reinstall packages
  remove - remove packages
  autoremove - Remove automatically all unused packages
  update - update list of available packages
  upgrade - upgrade the system by installing/upgrading packages
  full-upgrade - upgrade the system by removing/installing/upgrading packages
  edit-sources - edit the source information file
  satisfy - satisfy dependency strings

See apt(8) for more information about the available commands.
Configuration options and syntax is detailed in apt.conf(5).
Information about how to configure sources can be found in sources.list(5).
Package and version choices can be expressed via apt_preferences(5).
Security details are available in apt-secure(8).
                                        This APT has Super Cow Powers.

In [28]:
from sklearn import preprocessing
label_encoder = preprocessing.LabelEncoder()

label_encoder = preprocessing.LabelEncoder()
data_frame['Sex'] = label_encoder.fit_transform(data_frame['Sex'])

data_frame.head()

   ID  Sex   Age  Salary  Spending Score (1-100)
0   1    1  19.0    15.0                     NaN
1   2    1   NaN    15.0                    81.0
2   3    0  20.0    16.0                     6.0
3   4    0  23.0     NaN                    77.0
4   5    0   NaN     NaN                    40.0

In [38]:
data_frame.rename({'Spending Score (1-100)':'Spending_Score'}, axis=1, inplace=True)
data_frame.head()

   ID  Sex   Age  Salary  Spending_Score
0   1    1  19.0    15.0             NaN
1   2    1   NaN    15.0            81.0
2   3    0  20.0    16.0             6.0
3   4    0  23.0     NaN            77.0
4   5    0   NaN     NaN            40.0

In [39]:
low_spenders_data= data_frame[data_frame.Spending_Score < 70]
low_spenders_data.describe()

               ID         Sex         Age      Salary  Spending_Score
count  145.000000  145.000000  143.000000  144.000000      145.000000
mean    97.193103    0.448276   42.321678   59.763889       38.020690
std     52.330188    0.499041   14.760340   23.184268       18.394772
min      3.000000    0.000000   18.000000   16.000000        1.000000
25%     57.000000    0.000000   31.000000   44.000000       22.000000
50%     93.000000    0.000000   43.000000   60.000000       42.000000
75%    135.000000    1.000000   52.500000   73.000000       52.000000
max    199.000000    1.000000   70.000000  137.000000       69.000000

In [40]:
high_earners_low_spenders_data =  data_frame[(data_frame.Salary > 59.76) & (data_frame.Spending_Score < 70)]
high_earners_low_spenders_data.describe()

               ID        Sex        Age      Salary  Spending_Score
count   73.000000  73.000000  73.000000   73.000000       73.000000
mean   140.164384   0.493151  40.068493   77.287671       34.027397
std     32.965476   0.503413  13.849718   17.164627       18.828888
min     93.000000   0.000000  18.000000   60.000000        1.000000
25%    111.000000   0.000000  28.000000   63.000000       16.000000
50%    135.000000   0.000000  40.000000   73.000000       39.000000
75%    170.000000   1.000000  49.000000   87.000000       49.000000
max    199.000000   1.000000  68.000000  137.000000       69.000000

In [41]:
#Creates a new column with all the values equal to 1
data_frame['NewColumn'] = 1
data_frame.head()

   ID  Sex   Age  Salary  Spending_Score  NewColumn
0   1    1  19.0    15.0             NaN          1
1   2    1   NaN    15.0            81.0          1
2   3    0  20.0    16.0             6.0          1
3   4    0  23.0     NaN            77.0          1
4   5    0   NaN     NaN            40.0          1

In [42]:
def satisfaction(value):
  if value > 70:
    return "Satisfied"
  else:
    return "Unsatisfied"

In [44]:
data_frame['Spending_Score'].apply(satisfaction)

0      Unsatisfied
1        Satisfied
2      Unsatisfied
3        Satisfied
4      Unsatisfied
          ...
195      Satisfied
196    Unsatisfied
197      Satisfied
198    Unsatisfied
199      Satisfied
Name: Spending_Score, Length: 200, dtype: object

In [45]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 150)

In [47]:
data_frame['Customer_Satisfaction'] = data_frame['Spending_Score'].apply(satisfaction)
data_frame.head()

   ID  Sex   Age  Salary  Spending_Score  NewColumn Customer_Satisfaction
0   1    1  19.0    15.0             NaN          1           Unsatisfied
1   2    1   NaN    15.0            81.0          1             Satisfied
2   3    0  20.0    16.0             6.0          1           Unsatisfied
3   4    0  23.0     NaN            77.0          1             Satisfied
4   5    0   NaN     NaN            40.0          1           Unsatisfied

In [48]:
#This will save the dataset without the raws indeces
data_frame.to_csv(r'/content/Prepared_Mall_Customers.csv', index=False)